# Generated by Django 5.1 on 2024-08-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_category_contact_post_author_post_slug_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='post',
            field=models.CharField(max_length=50),
        ),
    ]
