# Generated by Django 5.1 on 2024-08-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_commentpost_author_alter_commentpost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='author',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commentpost',
            name='post',
            field=models.CharField(max_length=50),
        ),
    ]
